### ISSUE TITLE
Does not support Next@13.0.6

### ISSUE THREAD

**Issue by abdelrahman-osama** [ensite-in/next-firebase-auth-edge#3]
Installing the packages errors with I tried to install with next@13.0.6, I had to downgrade to 13.0.5.

**Comment by awinogrodzki** [comment]
Thanks for reporting @abdelrahman-osama 

I am looking into the issue at this very moment. Stay put!

**Comment by awinogrodzki** [comment]
Issue should be resolved by installing `next-firebase-auth-edge@0.2.9`

Here's the commit that fixes the issue: https://github.com/ensite-in/next-firebase-auth-edge/commit/1e4af6047790fd5c147e76c8d9b6b9078101ad90

Turns out `next-firebase-auth-edge` had explicit dependency on Next.js version 13.0.5. Right now it should support all future minor/patch versions, ie. `13.x.x`
